"""init migrate for lab11

Revision ID: 62faa5754d47
Revises: 72d10dae4513
Create Date: 2023-11-23 05:02:40.328249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62faa5754d47'
down_revision = '72d10dae4513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
