"""init migrate for password hashing

Revision ID: acf5b39a6772
Revises: 873429c17605
Create Date: 2023-11-19 19:26:30.127028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf5b39a6772'
down_revision = '873429c17605'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('user', 'password', new_column_name='password_hash')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('password_hash')
